
= Hawkular UI Services


[.lead]

image::https://www.bithound.io/github/hawkular/hawkular-ui-services/badges/score.svg[link="https://www.bithound.io/github/hawkular/hawkular-ui-services"]
image::https://www.bithound.io/github/hawkular/hawkular-ui-services/badges/dependencies.svg[link="https://www.bithound.io/github/hawkular/hawkular-ui-services/master/dependencies/npm"]

*Hawkular UI Services* is the home of Hawkular's Angular.js UI services. It wraps the Hawkular REST services with ngResource wrappers to provide a simplified REST interface to the the Hawkular Modules. These UI data services comprise the Hawkular console for https://github.com/hawkular/hawkular[Hawkular] and can be used as the basis for any Hawkular based data Angular data service.

Hawkular UI Services provides Angular ngResouce wrappers for the following Hawkular REST Resources:

* http://www.hawkular.org/docs/rest/rest-inventory.html[Hawkular Inventory]
* http://www.hawkular.org/docs/rest/rest-metrics.html[Hawkular Metrics]
* http://www.hawkular.org/docs/rest/rest-alerts.html[Hawkular Alerts]
* Hawkular Agent Deployment WebServices

== Buildig Hawkular-UI-Services

```shell
npm install
bower install
gulp
```

IMPORTANT: Gulp version 3.9.0+ is required (because we are using an ES6 gulpfile)

The service can be tested with the server. To run the actual testsuite you need to have relevant (that means hawkular-metrics,
hawkular-inventory, ...) server running. It must have a clean database (= no tenants, no metrics, ...).
Once the server is up and running, execute the relevant rest sub-target:

```shell
gulp rest:inventory
gulp rest:metric
gulp rest:alert
```

to start the testsuite. You can also specify the server's hostname (`--hostname)` or port (`--port`) when running the gulp command or by environment properties called `HAWKULAR_TEST_HOSTNAME` and `HAWKULAR_TEST_PORT`. If not specified, host and port default to `localhost:8080`.
